# prod profile 生产配置
wuage:
  profile: /home/wuage/uploadPath

server:
  port: 10808

spring:
  # 服务模块
  devtools:
    livereload:
      enabled: false
    restart:
      # 热部署开关
      enabled: false

  datasource:
    druid:
      url: jdbc:mysql://192.168.10.2:3306/wuage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: ENC(CpKiNUIlmO78EF+QC8dc6krc+xKnHmGPFuM/SFeBHkw=)


logging:
  level:
    com.wuage: info
    org.springframework: info