# dev profile 开发配置
wuage:
  profile: D:/wuage/uploadPath

server:
  port: 80

spring:
  # 服务模块
  devtools:
    livereload:
      enabled: true
    restart:
      # 热部署开关
      enabled: true
      additional-paths: src/main/java
  datasource:
    druid:
      url: jdbc:mysql://192.168.77.2:3306/wuage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: ENC(Y8xk570RkMcb2n2+/BtL1Q==)
#  redis:
#    lettuce:
#      pool:

logging:
  level:
    com.wuage: debug
    org.springframework: debug

